<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Markdig" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Maf.Lab.Domain\Maf.Lab.Domain.csproj" />
    <ProjectReference Include="..\Maf.Lab.Retrieval\Maf.Lab.Retrieval.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Maf.Lab.Tests" />
    <InternalsVisibleTo Include="Maf.Lab.IntegrationTests" />
  </ItemGroup>
</Project>
