/** The words portfolio's cards are labelled with, in each language. */
export const words = {
  bg: {
    assetClass: 'Клас активи',
    value: 'Стойност',
    target: 'Цел',
    actual: 'Текущо',
    drift: 'Отклонение',
    trade: 'Сделка',
    after: 'След',
    total: 'Общо',
    buy: 'Покупка',
    sell: 'Продажба',
    none: '—',
    outside: 'извън толеранса',
    rebalanceNeeded: 'Нужно е ребалансиране',
    rebalanceNotNeeded: 'Не е нужно ребалансиране',
    tolerance: 'толеранс',
    asOf: 'към',
    copy: 'Копирай като CSV',
    copied: 'Копирано',
    quarterEnd: 'Край на тримесечие',
    aum: 'AUM',
    change: 'Промяна',
    aumOf: 'AUM по тримесечия',
    account: 'Сметка',
    name: 'Име',
    household: 'Домакинство',
    model: 'Модел',
    currency: 'Валута',
    myAccounts: 'Моите сметки',
    focus: 'Фокус',
    inFocus: 'Във фокус',
    clearFocus: 'Изчисти фокуса',
  },
  en: {
    assetClass: 'Asset class',
    value: 'Value',
    target: 'Target',
    actual: 'Actual',
    drift: 'Drift',
    trade: 'Trade',
    after: 'After',
    total: 'Total',
    buy: 'Buy',
    sell: 'Sell',
    none: '—',
    outside: 'outside tolerance',
    rebalanceNeeded: 'Rebalance needed',
    rebalanceNotNeeded: 'No rebalance needed',
    tolerance: 'tolerance',
    asOf: 'as of',
    copy: 'Copy as CSV',
    copied: 'Copied',
    quarterEnd: 'Quarter end',
    aum: 'AUM',
    change: 'Change',
    aumOf: 'Quarter-end AUM',
    account: 'Account',
    name: 'Name',
    household: 'Household',
    model: 'Model',
    currency: 'Currency',
    myAccounts: 'My accounts',
    focus: 'Focus',
    inFocus: 'In focus',
    clearFocus: 'Clear focus',
  },
} as const;
