<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="A2A" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Maf.Lab.A2A\Maf.Lab.A2A.csproj" />
    <ProjectReference Include="..\Maf.Lab.Domain\Maf.Lab.Domain.csproj" />
    <ProjectReference Include="..\Maf.Lab.Hosting\Maf.Lab.Hosting.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Maf.Lab.Tests" />
  </ItemGroup>
</Project>
